### ISSUE TITLE
Version 16.6.6 does not compile

### ISSUE THREAD

**Issue by Kalle72** [lavv17/le#26]
Hello,

version 16.6.6 does not compile on my gentoo-pc -- but Version 16.6.5 do. I attached the build.log. I thought that you eventually know, how to circumvent this problem?

Thanks in advance and kind regards
Kalle72

**Comment by Kalle72** [comment]
The last lines of the log are

x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../lib -I/usr/include/ncursesw   -march=core2 -O2 -pipe -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o keymapdf.o keymapdf.cc
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../lib -I/usr/include/ncursesw   -march=core2 -O2 -pipe -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o mainmenu.o mainmenu.cc
x86_64-pc-linux-gnu-gcc  -march=core2 -O2 -pipe -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines  -Wl,-O1 -Wl,--as-needed -o le about.o block.o calc.o chset.o cmd.o color.o edit.o editcalc.o ext.o file.o format.o frames.o getch.o getstr.o help.o history.o kern.o keymap.o keymapdf.o keymapfn.o loadsave.o mainmenu.o menu.o menu1.o options.o pipe.o rus.o screen.o search.o signals.o tables.o textpoin.o user.o window.o highli.o clipbrd.o keynames.o mouse.o colormnu.o bm.o mb.o undo.o regex.o wcwidth.o wcwidth1.o ../lib/libgnu.a -L/usr/lib64  -lncursesw -ltinfo     -lm -lsupc++ 
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: highli.o: in function `ReadSyntaxFile(char const*, _IO_FILE*, syntax_hl**)':
highli.cc:(.text+0xfe3): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: highli.o: in function `std::pair<std::_Rb_tree_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, bool> std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_insert_unique<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
highli.cc:(.text._ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE16_M_insert_uniqueIS5_EESt4pairISt17_Rb_tree_iteratorIS5_EbEOT_[_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE16_M_insert_uniqueIS5_EESt4pairISt17_Rb_tree_iteratorIS5_EbEOT_]+0x182): undefined reference to `std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: highli.cc:(.text._ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE16_M_insert_uniqueIS5_EESt4pairISt17_Rb_tree_iteratorIS5_EbEOT_[_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE16_M_insert_uniqueIS5_EESt4pairISt17_Rb_tree_iteratorIS5_EbEOT_]+0x1b6): undefined reference to `std::_Rb_tree_decrement(std::_Rb_tree_node_base*)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1280: le] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-editors/le-1.16.6/work/le-1.16.6/src'
make[1]: *** [Makefile:1234: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-editors/le-1.16.6/work/le-1.16.6'
make: *** [Makefile:1188: all] Error 2

**Comment by Kalle72** [comment]
Problem still alive with 16.6.7

**Comment by polluks** [comment]
The last command should use g++ not gcc
`gcc  -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines   -o le about.o block.o calc.o chset.o cmd.o color.o edit.o editcalc.o ext.o file.o format.o frames.o getch.o getstr.o help.o history.o kern.o keymap.o keymapdf.o keymapfn.o loadsave.o mainmenu.o menu.o menu1.o options.o pipe.o rus.o screen.o search.o signals.o tables.o textpoin.o user.o window.o highli.o clipbrd.o keynames.o mouse.o colormnu.o bm.o mb.o undo.o regex.o wcwidth.o wcwidth1.o ../lib/libgnu.a -lncurses     -lm -lsupc++`

Workaround: Call the linker manually

**Comment by Kalle72** [comment]
@polluks: Thanks for your comment. Unfortunately I am not very sophisticated in programming. Therefore, I have two "questions":
1) The error is a software-bug and not a handling error on my part!?
2) How do I "Call the linker manually"?

**Comment by polluks** [comment]
1. Indeed, I suppose something with autoconf goes wrong.
2. Rather simple: Copy and paste the last line and replace `x86_64-pc-linux-gnu-gcc` with `x86_64-pc-linux-gnu-g++`. Now the compiler driver should add the right libs.
